import React,{useState,useEffect,useRef,lazy,Suspense} from 'react';
import {useReducedMotion,motion} from 'motion/react';
import {ArrowUpRight,ArrowDown,ArrowRight,Check,Home,Layers,Palette,MessageCircle,Pause,Play,Copy,Plus,X,Mail,Phone,Instagram} from 'lucide-react';
import BlurText from './BlurText.jsx';
import JellyRadio from './components/JellyRadio.jsx';
import Dock from './components/Dock.jsx';
import ShinyText from './components/ShinyText.jsx';
import PeekRating from './components/PeekRating.jsx';
import SquishSwitch from './components/SquishSwitch.jsx';
import IntroVideo from './components/IntroVideo.jsx';
import {plans,money} from './data.js';
const Prism=lazy(()=>import('./components/Prism.jsx'));
const OptionWheel=lazy(()=>import('./components/OptionWheel.jsx'));
const CometDial=lazy(()=>import('./components/CometDial.jsx'));
const FolderFloat=lazy(()=>import('./components/FolderFloat.jsx'));
const AccordionGallery=lazy(()=>import('./components/AccordionGallery.jsx'));
const DriftWall=lazy(()=>import('./components/DriftWall.jsx'));
const SlideCommit=lazy(()=>import('./components/SlideCommit.jsx'));
const gallery=[{image:'/assets/devices-blue.webp',label:'Diseño web',alt:'Concepto visual BettoX en ordenador y móvil'},{image:'/assets/logo.webp',label:'Identidad de marca',alt:'Logo original de BettoX'}];
const wallItems=Array.from({length:6},(_,i)=>({image:gallery[i%2].image,title:''}));
const types=['Negocio local','Marca personal','Empresa','Catálogo','Menú de cartas'];
function useMedia(query){const [value,setValue]=useState(()=>matchMedia(query).matches);useEffect(()=>{const m=matchMedia(query),change=()=>setValue(m.matches);m.addEventListener('change',change);return()=>m.removeEventListener('change',change)},[query]);return value}
function Near({children,className='',decorative=false,enabled=true}){const ref=useRef(null);const [visible,setVisible]=useState(false);const [loaded,setLoaded]=useState(false);const [pageVisible,setPageVisible]=useState(!document.hidden);useEffect(()=>{const io=new IntersectionObserver(([e])=>{setVisible(e.isIntersecting);if(e.isIntersecting)setLoaded(true)},{rootMargin:'80px'});io.observe(ref.current);const change=()=>setPageVisible(!document.hidden);document.addEventListener('visibilitychange',change);return()=>{io.disconnect();document.removeEventListener('visibilitychange',change)}},[]);return <div ref={ref} className={className}>{(decorative?visible&&pageVisible&&enabled:loaded)&&<Suspense fallback={null}>{children}</Suspense>}</div>}
class VisualBoundary extends React.Component{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?null:this.props.children}}
function Reveal({children,className=''}){const reduce=useReducedMotion();return <motion.div className={className} initial={reduce?false:{opacity:0,y:22,filter:'blur(5px)'}} whileInView={{opacity:1,y:0,filter:'blur(0px)'}} viewport={{once:true,amount:.1}} transition={{duration:.65,ease:[.16,1,.3,1]}}>{children}</motion.div>}
export default function App(){
 const mobile=useMedia('(max-width:700px)'),reduce=useReducedMotion();
 const [light,setLight]=useState(false),[wheelKey,setWheelKey]=useState(0);
 useEffect(()=>{document.documentElement.dataset.theme=light?'light':'dark'},[light]);
 const [paused,setPaused]=useState(false),[viewed,setViewed]=useState(null),[chosen,setChosen]=useState(null),[brandChoice,setBrandChoice]=useState(null),[brandAdded,setBrandAdded]=useState(false),[type,setType]=useState(null),[ready,setReady]=useState(false),[status,setStatus]=useState('');
 const current=viewed===null?null:plans[viewed],selected=chosen===null?null:plans[chosen],motionOn=!paused&&!reduce;
 const request=`Hola BettoX. ${selected?`Me interesa el ${selected.name} (${money(selected.price)}). `:'Quiero consultar un proyecto. '}${brandAdded&&brandChoice?`También quiero presupuesto para ${brandChoice.toLowerCase()}. `:''}${type!==null?`Mi proyecto: ${types[type].toLowerCase()}. `:''}¿Qué necesitáis para empezar?`;
 const whatsapp='https://wa.me/34617026852?text='+encodeURIComponent(request);
 useEffect(()=>{setReady(false);setStatus('')},[chosen,brandAdded,brandChoice,type]);
 const go=id=>{const el=document.getElementById(id);if(!el)return;el.scrollIntoView({behavior:reduce?'instant':'smooth',block:'start'});el.focus({preventScroll:true});history.replaceState(null,'','#'+id)};
 const inspect=(i,scroll=true)=>{setViewed(i);if(scroll)requestAnimationFrame(()=>go('plan-info'))};
 const choose=()=>{setChosen(viewed);setReady(false)};
 const valid=chosen!==null&&type!==null;
 const prepare=()=>{if(!valid){setStatus('Elige un plan y el tipo de proyecto para continuar.');return Promise.reject(new Error('Faltan elecciones'))}const link=document.createElement('a');link.href=whatsapp;link.target='_blank';link.rel='noopener noreferrer';document.body.appendChild(link);link.click();link.remove();return Promise.resolve()};
 const shortcut=v=>{if(v==='Otros'){const el=document.getElementById('project-type');el.open=true;go('project-type')}else{setType(types.indexOf(v));setWheelKey(k=>k+1)}};
 async function copy(){try{await navigator.clipboard.writeText(request);setStatus('Solicitud copiada.')}catch{setStatus(request)}}
 const dock=[{icon:<><Home size={18}/><small>Inicio</small></>,label:'Inicio',onClick:()=>go('inicio')},{icon:<><Layers size={18}/><small>Planes</small></>,label:'Planes',onClick:()=>go('planes')},{icon:<><Palette size={18}/><small>Marca</small></>,label:'Marca',onClick:()=>go('marca')},{icon:<><MessageCircle size={18}/><small>Contacto</small></>,label:'Contacto',onClick:()=>go('contacto')}];
 const channels=[{name:'TikTok',detail:'@its.albertto',href:'https://www.tiktok.com/@its.albertto',icon:<span className="tiktok-symbol" aria-hidden="true">♪</span>},{name:'Instagram',detail:'@its.albertto',href:'https://www.instagram.com/its.albertto/',icon:<Instagram/>},{name:'Gmail',detail:'albertosukerman@gmail.com',href:'mailto:albertosukerman@gmail.com?subject='+encodeURIComponent('Consulta BettoX')+'&body='+encodeURIComponent(request),icon:<Mail/>},{name:'Teléfono',detail:'+34 617 02 68 52',href:'tel:+34617026852',icon:<Phone/>}];
 return <div className={motionOn?'site':'site motion-paused'}>
 <a className="skip" href="#planes">Ir a los planes</a>
 <header className="wrap header"><a href="#inicio" className="brand" aria-label="BettoX, inicio"><img src="/assets/logo.webp" alt="BettoX" width="840" height="280"/></a><SquishSwitch checked={light} onChange={setLight} label="Modo claro" ariaLabel="Modo claro" width={58} height={32} trackColor="#27272a" trackOnColor="#c4b5fd" thumbColor="#b4adbf" thumbOnColor="#312044"/><nav aria-label="Navegación principal"><a href="#planes">Planes</a><a href="#marca">Diseño de marca</a><a href="#contacto" className="pill">Hablemos <ArrowUpRight size={16}/></a></nav></header>
 <main>
 <section id="inicio" className="hero" tabIndex={-1}>
  <div className="prism-backdrop" aria-hidden="true"><VisualBoundary><Near decorative enabled={motionOn} className="prism-stage"><Prism animationType="rotate" timeScale={.5} height={3.5} baseWidth={5.5} scale={1.5} hueShift={0} colorFrequency={1} noise={0} glow={1} suspendWhenOffscreen/></Near></VisualBoundary></div>
  <div className="wrap hero-grid"><div className="hero-copy"><p className="eyebrow">DISEÑO WEB · IDENTIDAD · BETTOX</p><h1><BlurText text="Tal vez sea tu señal." delay={150}/><br/><BlurText text="No la dejes pasar." delay={130}/></h1><p>Diseñamos la web y la imagen<br className="desktop"/> que tu negocio está buscando.</p><a className="button primary" href="#planes">Descubre tu plan <ArrowDown size={17}/></a><span className="hero-price">Desde 55,00 € · 50 % al inicio</span></div>
  <div className="film-column"><IntroVideo/></div></div>
  <div className="wrap hero-foot"><span>Móvil primero. Tu estilo, siempre.</span><button className="motion-toggle" onClick={()=>setPaused(!paused)} aria-pressed={paused}>{paused?<Play size={14}/>:<Pause size={14}/>} {paused?'Activar efectos':'Pausar efectos'}</button></div>
 </section>
 <section id="planes" className="wrap section plans" tabIndex={-1}>
  <div className="section-heading"><div><p className="eyebrow">CINCO PLANES. TU ELECCIÓN.</p><BlurText as="h2" text="Tu idea, el plan que encaja." delay={80}/></div><div className="dial-mini"><Near><CometDial value={viewed===null?0:viewed+1} min={0} max={5} step={1} unit="" label="Explorar planes: cero sin vista, uno a cinco para ver un plan" size={94} thickness={3} onChange={v=>{if(v>0)inspect(Math.round(v)-1,false);else setViewed(null)}}/></Near><span>Gira para explorar<br/><small>O pulsa «Ver info»</small></span></div></div>
  <div className="plan-list">{plans.map((p,i)=><Reveal key={p.name} className={chosen===i?'plan-card selected':'plan-card'}><label className="plan-pick"><input type="radio" name="plan" required checked={chosen===i} onChange={()=>setChosen(i)} aria-label={"Elegir "+p.name}/><span aria-hidden="true"/></label><h3>{p.name}</h3><strong>{money(p.price)}</strong><button className="info-link" onClick={()=>inspect(i)} aria-label={'Ver info de '+p.name}>Ver info <ArrowDown size={15}/></button>{chosen===i&&<span className="selected-tag"><Check size={13}/> Añadido</span>}</Reveal>)}</div>
  <div id="plan-info" className={current?'plan-info populated':'plan-info'} tabIndex={-1}>
  {current?<><div className="info-overview"><p className="eyebrow">CONOCE ESTE PLAN</p><h3>{current.name}</h3><p className="info-price">{money(current.price)}</p><p>{current.ideal}</p><button className={chosen===viewed?'button selected-button':'button primary'} onClick={choose}>{chosen===viewed?<><Check size={17}/> Añadido a tu consulta</>:<>Me interesa este plan <Plus size={17}/></>}</button>{chosen===viewed&&<a className="text-link" href="#contacto">Ver mi consulta <ArrowUpRight size={15}/></a>}</div><div className="info-includes"><p className="includes-label">Todo lo que incluye</p><ul>{current.features.map(f=><li key={f}><Check size={14}/><span>{f}</span></li>)}</ul></div></>:<p><Layers size={20}/> Pulsa «Ver info» para descubrir un plan. Tú decides cuál añadir.</p>}
  </div>
  <details className="terms"><summary>Qué debes saber antes de empezar <Plus size={16}/></summary><div><p>50 % al inicio y 50 % al entregar tu enlace funcionando. Todos los planes incluyen adaptación a móvil, enlace público y QR.</p><p>En Plan Express y Plan Essential aportas los textos y fotos listos para utilizar. La preparación para Google no garantiza indexación, posiciones ni aparición en respuestas de IA.</p><p>Pago: Zelle, Binance/USDT, efectivo o pago móvil con intermediario local; concretamos el método contigo.</p></div></details>
 </section>
 <section id="marca" className="section brand-section" tabIndex={-1}><div className="wrap"><div className="brand-grid"><div className="brand-copy"><p className="eyebrow">EL RESTO TAMBIÉN HABLA DE TI</p><BlurText as="h2" text="Una marca. En todas partes." delay={85}/><p>Logo, tarjeta y QR opcional. Una imagen que conecta tu web con todo lo demás.</p><JellyRadio items={['Logo','Tarjeta','Logo y tarjeta']} value={brandChoice} allowEmpty onChange={setBrandChoice} ariaLabel="Diseño de marca" size="lg" swell={.14} barge={4} jelly={motionOn?1:0}/><label className={brandChoice?'brand-check':'brand-check muted'}><input type="checkbox" disabled={!brandChoice} checked={brandAdded} onChange={e=>setBrandAdded(e.target.checked)}/><span>Añadir diseño de marca a mi consulta<small>{brandChoice?brandChoice+' · presupuesto aparte':'Elige primero qué necesitas.'}</small></span></label><p className="fine-print">Servicio de diseño. Impresión no incluida.</p></div>
  <div className="brand-visuals"><div className="folder-block"><Near className="folder-slot"><FolderFloat items={['Marca personal','Menú de cartas','Otros']} label="Tu proyecto" sublabel="Toca para elegir" trigger="click" physics={false} drift={0} width={160} height={112} spread={mobile?95:130} lift={22} onSelect={shortcut}/></Near><p className="folder-selection" aria-live="polite">{type!==null?'Elegido: '+types[type]:'Elige por dónde empezar'}</p></div><div className="sample-reviews"><p className="eyebrow">EJEMPLOS DE RESEÑAS</p>{['Una web clara, rápida y con un diseño que destaca.','Todo se ve genial desde el móvil. Fácil de navegar.'].map(t=><div className="sample-review" key={t}><PeekRating value={5} readOnly size={20} gap={3} ariaLabel="Ejemplo visual: cinco estrellas"/><p>«{t}»</p></div>)}<small>Textos de muestra, no opiniones de clientes.</small></div></div>
 </div></div></section>
 <section id="contacto" className="section contact-section" tabIndex={-1}><div className="contact-wall" aria-hidden="true"><Near decorative enabled={motionOn} className="wall-stage"><DriftWall items={wallItems} columns={mobile?3:5} tileWidth={180} tileHeight={120} speed={20} tilt={16} turn={-14} parallax={0}/></Near></div><div className="wrap contact-grid"><div className="contact-copy"><p className="eyebrow">VAMOS A HABLAR</p><BlurText as="h2" text="Tu próxima web empieza aquí." delay={90}/><div className="channels">{channels.map((channel,i)=><motion.a key={channel.name} href={channel.href} target={i<2?'_blank':undefined} rel={i<2?'noopener noreferrer':undefined} initial={reduce?false:{opacity:0,x:-20,filter:'blur(6px)'}} whileInView={{opacity:1,x:0,filter:'blur(0px)'}} viewport={{once:true}} transition={{duration:.55,delay:motionOn?i*.12:0}} className="channel">{channel.icon}<span><ShinyText text={channel.name} speed={2} delay={1} disabled={!motionOn} color={light?"#554762":"#b5b5b5"} shineColor={light?"#171020":"#ffffff"}/><small>{channel.detail}</small></span><ArrowUpRight size={19}/></motion.a>)}</div></div>
 <div className="request-card"><p className="eyebrow">TU CONSULTA, A TU MEDIDA</p><div className="selection-summary" aria-live="polite">{selected?<div><span>{selected.name}<small>{money(selected.price)}</small></span><button aria-label="Quitar plan de la consulta" onClick={()=>setChosen(null)}><X size={17}/></button></div>:<p className="required-prompt"><span>1 · Plan obligatorio</span><button className="text-link" onClick={()=>go('planes')}>Elige tu plan <ArrowUpRight size={15}/></button></p>}{brandAdded&&brandChoice&&<div><span>{brandChoice}<small>Diseño de marca · a presupuestar</small></span><button aria-label="Quitar diseño de marca" onClick={()=>{setBrandAdded(false);setBrandChoice(null)}}><X size={17}/></button></div>}</div>
 <details id="project-type" className="project-type" open tabIndex={-1}><summary><span>2 · ¿Qué tipo de proyecto tienes?<small>Obligatorio · {type!==null?types[type]:'Elige una opción'}</small></span><Plus size={15}/></summary><Near className="wheel-slot"><OptionWheel key={wheelKey} items={types} loop defaultSelected={type} onChange={setType} textColor={light?'#62566e':'#a6a6a6'} activeColor={light?'#1a1025':'#ffffff'} fontSize={1.05} spacing={2.65} inset={16} tilt={6} blur={motionOn?1:0} smoothing={motionOn?180:1} draggable={!mobile}/></Near></details>
 <p className="requirement-status" aria-live="polite">{valid?'Todo listo. Abre WhatsApp con tu consulta.':chosen===null&&type===null?'Elige un plan y un tipo de proyecto.':chosen===null?'Falta elegir tu plan.':'Falta elegir el tipo de proyecto.'}</p><Near className="slide-slot"><SlideCommit key={`${chosen}-${brandAdded}-${brandChoice}-${type}`} label="Hablemos por WhatsApp" icon={<svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M20.5 3.5A11.8 11.8 0 0 0 12.1 0C5.6 0 .3 5.3.3 11.8c0 2.1.6 4.1 1.6 5.9L.2 24l6.5-1.7a11.8 11.8 0 0 0 5.4 1.3h.1C18.7 23.6 24 18.3 24 11.8c0-3.2-1.2-6.1-3.5-8.3ZM12.1 21.6c-1.8 0-3.5-.5-5-1.4l-.4-.2-3.9 1 1-3.8-.3-.4a9.8 9.8 0 1 1 8.6 4.8Zm5.4-7.3c-.3-.1-1.7-.8-2-.9-.3-.1-.5-.1-.7.2-.2.3-.8.9-1 1.1-.2.2-.4.2-.7.1-.3-.2-1.2-.5-2.3-1.4-.9-.8-1.5-1.7-1.7-2-.2-.3 0-.5.1-.6l.5-.6.3-.5c.1-.2 0-.4 0-.6L9.1 7c-.2-.5-.5-.5-.7-.5h-.6c-.2 0-.5.1-.8.4-.3.3-1 1-1 2.4s1 2.8 1.2 3c.1.2 2 3.1 4.9 4.3.7.3 1.2.5 1.6.6.7.2 1.3.2 1.8.1.6-.1 1.7-.7 1.9-1.4.3-.7.3-1.2.2-1.3-.1-.1-.3-.2-.6-.3Z"/></svg>} doneLabel="Abriendo WhatsApp" errorLabel="Elige plan y proyecto" disabled={!valid} width={mobile?Math.min(310,window.innerWidth-88):310} height={56} onConfirm={prepare}/></Near><button className="prepare-button" disabled={!valid} onClick={prepare} aria-label="Preparar consulta por WhatsApp con un toque">Desliza para preparar <ArrowRight size={14}/></button></div></div></section>
 </main><footer className="wrap footer"><a href="#inicio" className="wordmark">BettoX</a><span>© {new Date().getFullYear()} · Diseño a tu medida.</span><a href="#inicio">Volver arriba ↑</a></footer><nav className="dock-fixed" aria-label="Accesos rápidos"><Dock items={dock} baseItemSize={52} magnification={mobile||!motionOn?52:68} panelHeight={70} dockHeight={84}/></nav>
 </div>
}
